### ISSUE TITLE
tarball release?

### ISSUE THREAD

**Issue by alexmyczko** [anthonyc-r/netsurf-gnustep#1]
i am having trouble building it. will this be merged back to netsurf source? can you create a tarball that builds without internet/git?

**Comment by anthonyc-r** [comment]
Netsurf has quite a few dependencies, I’d recommend following the quick start guide at https://github.com/anthonyc-r/netsurf-gnustep/blob/gnustep/docs/quick-start.md - once you’ve got the standard gtk port building, you should be able to drop this version in and build the gnustep target.

**Comment by alexmyczko** [comment]
https://packages.debian.org/sid/netsurf-gtk being in the gnustep debian packaging team and maintainer of netsurf i am very interested in building the gnustep version officially. so i will have to create a source tarball myself. you don't plan getting it into official netsurf source?

**Comment by alexmyczko** [comment]
so i took the 3.10 source, and copied a master copy of your gnustep-netsurf into it and got this:
https://sid.ethz.ch/debian/netsurf-gnustep/netsurf_3.10%2Bds~gnustep-1_amd64.build

drop the filename from the url to view the files/tree of my copy or get it as the orig.tar.xz

i must be doing something wrong. does copying your master checkout over 3.10 netsurf source break something? will the framebuffer and gtk3 versions not build anymore after that action? HALP!!1

**Comment by eukara** [comment]
The steps for building NetSurf-GNUstep are the same as for regular NetSurf, however instead of cd'ing into the 'netsurf' directory under ~/dev-netsurf/workspace, you clone this repository and build the target inside netsurf-gnustep instead.

The complete set of commands on a local system looks like this:

```
$ wget https://git.netsurf-browser.org/netsurf.git/plain/docs/env.sh
$ unset HOST
$ source env.sh
$ ns-package-install
$ ns-clone
$ ns-pull-install
$ rm env.sh
$ cd ~/dev-netsurf/workspace
$ source env.sh
(this is where it differs, instead of going into netsurf, we clone and cd into netsurf-gnustep)
$ git clone https://github.com/anthonyc-r/netsurf-gnustep
$ cd ./netsurf-gnustep
$ ./gnustepbuild.sh
```

Hope this helps in some capacity.

**Comment by anthonyc-r** [comment]
I did have a little play around with a debian chroot. Having grabbed the source with apt-get source, and updated ‘netsurf-3.10/netsurf’ with this project, I was able to build with ‘dpkg-buildpackage -b -uc -us’.

Well, I didn’t get that dependency error you saw anyway, it does fail to build against the 3.10 tree due to some changes to libcss. But this is somewhat expected, I’ll perhaps create a branch that builds against 3.10.

But yeah, not sure why you were getting that issue when trying this same method… 🤔

**Comment by eukara** [comment]
Also, since I have an opportunity to voice this now: Thank you for the work on the GNUstep version of NetSurf! I've been using it to read lots of documentation :)

**Comment by alexmyczko** [comment]
```
BUILD CC: build/Linux-gnustep/tools/split-messages
MSGSPLIT: Language: de Filter: any
MSGSPLIT: Language: en Filter: any
MSGSPLIT: Language: fr Filter: any
MSGSPLIT: Language: it Filter: any
MSGSPLIT: Language: nl Filter: any
MSGSPLIT: Language: zh_CN Filter: any
    LINK: NetSurf
/usr/bin/ld: build/Linux-gnustep/_var_www_debian_netsurf-gnustep_1_netsurf-gnustep_frontends_gnustep_PlotView.o: in function `-[PlotView dumpContentType:]':
/var/www/debian/netsurf-gnustep/1/netsurf-gnustep/frontends/gnustep/PlotView.m:733: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: warning: libobjc.so.4, needed by /usr/lib/libgnustep-gui.so, may conflict with libobjc.so.4.6
/usr/bin/ld: build/Linux-gnustep/_var_www_debian_netsurf-gnustep_1_netsurf-gnustep_frontends_gnustep_AppDelegate.o: undefined reference to symbol '__objc_class_name_Protocol'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libobjc.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make: *** [Makefile:368: NetSurf] Error 1
```

**Comment by anthonyc-r** [comment]
I put together a tarball that builds 'standalone' this morning which you might be able to try, I'll upload it after work today.

**Comment by anthonyc-r** [comment]
Hey, could you see if this works? 
https://github.com/anthonyc-r/netsurf-gnustep/releases/download/3.10/netsurf-3.10.tar.gz

You should be able to run 'make TARGET=gnustep' from the base dir (not inside the netsurf subdir) to build, which should spit out NetSurf.app into the netsurf subddirectory...

**Comment by alexmyczko** [comment]
i believe it works, and is only a problem on my specific system, which ends with:

```
    LINK: NetSurf
/usr/bin/ld: build/Linux-gnustep/_var_www_debian_netsurf-gnustep_3_netsurf-3.10_netsurf_frontends_gnustep_PlotView.o: in function `-[PlotView dumpContentType:]':
/var/www/debian/netsurf-gnustep/3/netsurf-3.10/netsurf/frontends/gnustep/PlotView.m:733: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: warning: libobjc.so.4, needed by /usr/lib/libgnustep-gui.so, may conflict with libobjc.so.4.6
/usr/bin/ld: build/Linux-gnustep/_var_www_debian_netsurf-gnustep_3_netsurf-3.10_netsurf_frontends_gnustep_AppDelegate.o: undefined reference to symbol '__objc_class_name_Protocol'
/usr/bin/ld: /usr/lib/x86_64-linux-gnu/libobjc.so.4: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:715: NetSurf] Error 1
make[1]: Leaving directory '/var/www/debian/netsurf-gnustep/3/netsurf-3.10/netsurf'
make: *** [Makefile:125: /var/www/debian/netsurf-gnustep/3/netsurf-3.10/inst-gnustep/build-stamp] Error 2
```

on ubuntu 20.04 it ends here:
```
/scratch/ns/netsurf-3.10/netsurf/frontends/gnustep/AppDelegate.m:237:6: warning: this statement may fall through [-Wimplicit-fallthrough=]
  237 |   if (current != nil) {
      |      ^
/scratch/ns/netsurf-3.10/netsurf/frontends/gnustep/AppDelegate.m:241:2: note: here
  241 |  case ViewLocationWindow:
      |  ^~~~
make[1]: *** [Makefile:870: build/Linux-gnustep/_scratch_ns_netsurf-3.10_netsurf_frontends_gnustep_AppDelegate.o] Error 1
make[1]: Leaving directory '/scratch/ns/netsurf-3.10/netsurf'
make: *** [Makefile:125: /scratch/ns/netsurf-3.10/inst-gnustep/build-stamp] Error 2
```

many thanks!

looks much better dropping my experimental libobjc2 libs:
```
cc1: warning: command-line option ‘-fobjc-exceptions’ is valid for ObjC/ObjC++ but not for C
cc1: warning: command-line option ‘-fconstant-string-class=NSConstantString’ is valid for ObjC/ObjC++ but not for C
cc1: warning: command-line option ‘-fno-objc-gc’ is valid for LTO/ObjC/ObjC++ but not for C
In file included from /usr/include/assert.h:35,
                 from /var/www/debian/netsurf-gnustep/3/netsurf-3.10/netsurf/utils/utf8.c:23:
/usr/include/features.h:187:3: warning: #warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE" [-Wcpp]
  187 | # warning "_BSD_SOURCE and _SVID_SOURCE are deprecated, use _DEFAULT_SOURCE"
      |   ^~~~~~~
    LINK: NetSurf
/usr/bin/ld: build/Linux-gnustep/_var_www_debian_netsurf-gnustep_3_netsurf-3.10_netsurf_frontends_gnustep_PlotView.o: in function `-[PlotView dumpContentType:]':
/var/www/debian/netsurf-gnustep/3/netsurf-3.10/netsurf/frontends/gnustep/PlotView.m:733: warning: the use of `tmpnam' is dangerous, better use `mkstemp'
Generating Info.plist
Assembling NetSurf.app bundle
make[1]: Leaving directory '/var/www/debian/netsurf-gnustep/3/netsurf-3.10/netsurf'
touch /var/www/debian/netsurf-gnustep/3/netsurf-3.10/inst-gnustep/build-stamp
```
